server:
  port: 8081

spring:
  application:
    name: dev-fullstack-api

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          proc:
            param_null_passing: true
          format_sql: true

